// Package docs Soccer Manager API - Swagger documentation.
// Code generated by hand; run `swag init -g cmd/api/main.go --parseDependency` to regenerate from annotations.
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "title": "Soccer Manager API",
        "description": "RESTful API for fantasy football manager. Create teams, manage players, and trade on the transfer market.",
        "version": "1.0"
    },
    "host": "localhost:3000",
    "basePath": "/api/v1",
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "security": [{"BearerAuth": []}],
    "paths": {
        "/health": {
            "get": {
                "summary": "Health check",
                "description": "Returns API health status",
                "tags": ["health"],
                "produces": ["application/json"],
                "responses": {
                    "200": {"description": "OK", "schema": {"type": "object", "additionalProperties": {"type": "string"}}}
                }
            }
        },
        "/signup": {
            "post": {
                "summary": "Register",
                "description": "Create account with email/password. Automatically creates a team of 20 players (3 GK, 6 DEF, 6 MID, 5 ATT) and $5M budget.",
                "tags": ["auth"],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [{"in": "body", "name": "body", "required": true, "schema": {"$ref": "#/definitions/SignupRequest"}}],
                "responses": {
                    "201": {"description": "Created", "schema": {"$ref": "#/definitions/AuthResponse"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "409": {"description": "Conflict", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/login": {
            "post": {
                "summary": "Login",
                "description": "Authenticate with email and password, receive JWT token",
                "tags": ["auth"],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [{"in": "body", "name": "body", "required": true, "schema": {"$ref": "#/definitions/LoginRequest"}}],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/AuthResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/me": {
            "get": {
                "summary": "Current user",
                "description": "Returns the authenticated user ID from the JWT",
                "tags": ["auth"],
                "security": [{"BearerAuth": []}],
                "produces": ["application/json"],
                "responses": {
                    "200": {"description": "OK", "schema": {"type": "object", "properties": {"user_id": {"type": "integer"}}}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/users": {
            "post": {
                "summary": "Create user",
                "description": "Create a user account with email, password, fullname, age. Does not create a team; use POST /team to create a team for this user.",
                "tags": ["users"],
                "security": [{"BearerAuth": []}],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [{"in": "body", "name": "body", "required": true, "schema": {"$ref": "#/definitions/SignupRequest"}}],
                "responses": {
                    "201": {"description": "Created", "schema": {"$ref": "#/definitions/User"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "409": {"description": "Conflict", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/team": {
            "get": {
                "summary": "Get my team",
                "description": "Returns the authenticated user's team. Total value is the sum of all player market values.",
                "tags": ["team"],
                "security": [{"BearerAuth": []}],
                "produces": ["application/json"],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/Team"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            },
            "post": {
                "summary": "Create team",
                "description": "Create a team with 20 players (3 GK, 6 DEF, 6 MID, 5 ATT), $1M each. Send user_id, name, country, budget in body. Budget defaults to $5M if omitted or zero.",
                "tags": ["team"],
                "security": [{"BearerAuth": []}],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [{"in": "body", "name": "body", "required": true, "schema": {"$ref": "#/definitions/CreateTeamRequest"}}],
                "responses": {
                    "201": {"description": "Created", "schema": {"$ref": "#/definitions/Team"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "404": {"description": "User not found", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "409": {"description": "Conflict", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            },
            "put": {
                "summary": "Update team",
                "description": "Update team name and country (editable fields)",
                "tags": ["team"],
                "security": [{"BearerAuth": []}],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [{"in": "body", "name": "body", "required": true, "schema": {"$ref": "#/definitions/UpdateTeamRequest"}}],
                "responses": {
                    "200": {"description": "OK"},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/team/players": {
            "get": {
                "summary": "Get team players",
                "description": "Returns all players belonging to the authenticated user's team",
                "tags": ["team"],
                "security": [{"BearerAuth": []}],
                "produces": ["application/json"],
                "responses": {
                    "200": {"description": "OK", "schema": {"type": "array", "items": {"$ref": "#/definitions/Player"}}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/players": {
            "post": {
                "summary": "Create player",
                "description": "Add a player to your team. Age is random 18–40, initial market value $1M. Position: goalkeeper, defender, midfielder, attacker.",
                "tags": ["players"],
                "security": [{"BearerAuth": []}],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [{"in": "body", "name": "body", "required": true, "schema": {"$ref": "#/definitions/CreatePlayerRequest"}}],
                "responses": {
                    "201": {"description": "Created", "schema": {"$ref": "#/definitions/Player"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/players/{id}": {
            "put": {
                "summary": "Update player",
                "description": "Update player first name, last name, country (editable by team owner). Only your team's players.",
                "tags": ["players"],
                "security": [{"BearerAuth": []}],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {"in": "path", "name": "id", "required": true, "type": "integer"},
                    {"in": "body", "name": "body", "required": true, "schema": {"$ref": "#/definitions/UpdatePlayerRequest"}}
                ],
                "responses": {
                    "200": {"description": "OK"},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "403": {"description": "Forbidden", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/transfer/list": {
            "get": {
                "summary": "Get transfer market list",
                "description": "Returns all players currently on the transfer list with asking prices",
                "tags": ["transfer"],
                "security": [{"BearerAuth": []}],
                "produces": ["application/json"],
                "responses": {
                    "200": {"description": "OK", "schema": {"type": "array", "items": {"$ref": "#/definitions/TransferMarketItem"}}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            },
            "post": {
                "summary": "List player on transfer market",
                "description": "Put one of your players on the transfer list with an asking price. Player must belong to your team and not already be listed.",
                "tags": ["transfer"],
                "security": [{"BearerAuth": []}],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [{"in": "body", "name": "body", "required": true, "schema": {"$ref": "#/definitions/ListPlayerRequest"}}],
                "responses": {
                    "201": {"description": "Created"},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "403": {"description": "Forbidden", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "409": {"description": "Conflict", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/transfer/buy": {
            "post": {
                "summary": "Buy player",
                "description": "Purchase a player from the transfer list at the asking price. Budgets are updated; player's market value increases 10–100% on transfer.",
                "tags": ["transfer"],
                "security": [{"BearerAuth": []}],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [{"in": "body", "name": "body", "required": true, "schema": {"$ref": "#/definitions/BuyPlayerRequest"}}],
                "responses": {
                    "200": {"description": "OK"},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        }
    },
    "definitions": {
        "SignupRequest": {
            "type": "object",
            "required": ["email", "password"],
            "properties": {
                "email": {"type": "string", "example": "user@example.com"},
                "password": {"type": "string", "example": "secret123"},
                "fullname": {"type": "string"},
                "age": {"type": "integer"}
            }
        },
        "LoginRequest": {
            "type": "object",
            "required": ["email", "password"],
            "properties": {
                "email": {"type": "string"},
                "password": {"type": "string"}
            }
        },
        "AuthResponse": {
            "type": "object",
            "properties": {
                "user_id": {"type": "integer"},
                "email": {"type": "string"},
                "fullname": {"type": "string"},
                "age": {"type": "integer"},
                "token": {"type": "string"}
            }
        },
        "User": {
            "type": "object",
            "properties": {
                "id": {"type": "integer"},
                "email": {"type": "string"},
                "fullname": {"type": "string"},
                "age": {"type": "integer"},
                "created_at": {"type": "string", "format": "date-time"},
                "updated_at": {"type": "string", "format": "date-time"}
            }
        },
        "Team": {
            "type": "object",
            "properties": {
                "id": {"type": "integer"},
                "user_id": {"type": "integer"},
                "name": {"type": "string"},
                "country": {"type": "string"},
                "budget": {"type": "integer"},
                "total_value": {"type": "integer"},
                "created_at": {"type": "string", "format": "date-time"},
                "updated_at": {"type": "string", "format": "date-time"}
            }
        },
        "CreateTeamRequest": {
            "type": "object",
            "required": ["user_id"],
            "properties": {
                "user_id": {"type": "integer", "description": "User ID that will own the team"},
                "name": {"type": "string", "description": "Team name"},
                "country": {"type": "string", "description": "Team country"},
                "budget": {"type": "integer", "description": "Initial budget in dollars; defaults to 5000000 if omitted or zero"}
            }
        },
        "UpdateTeamRequest": {
            "type": "object",
            "properties": {
                "name": {"type": "string"},
                "country": {"type": "string"}
            }
        },
        "Player": {
            "type": "object",
            "properties": {
                "id": {"type": "integer"},
                "team_id": {"type": "integer"},
                "first_name": {"type": "string"},
                "last_name": {"type": "string"},
                "country": {"type": "string"},
                "age": {"type": "integer"},
                "position": {"type": "string"},
                "market_value": {"type": "integer"},
                "created_at": {"type": "string", "format": "date-time"},
                "updated_at": {"type": "string", "format": "date-time"}
            }
        },
        "CreatePlayerRequest": {
            "type": "object",
            "required": ["first_name", "last_name", "position"],
            "properties": {
                "first_name": {"type": "string"},
                "last_name": {"type": "string"},
                "country": {"type": "string"},
                "position": {"type": "string", "enum": ["goalkeeper", "defender", "midfielder", "attacker"]}
            }
        },
        "UpdatePlayerRequest": {
            "type": "object",
            "properties": {
                "first_name": {"type": "string"},
                "last_name": {"type": "string"},
                "country": {"type": "string"}
            }
        },
        "ListPlayerRequest": {
            "type": "object",
            "required": ["player_id", "asking_price"],
            "properties": {
                "player_id": {"type": "integer"},
                "asking_price": {"type": "integer"}
            }
        },
        "TransferMarketItem": {
            "type": "object",
            "properties": {
                "listing_id": {"type": "integer"},
                "player_id": {"type": "integer"},
                "asking_price": {"type": "integer"},
                "first_name": {"type": "string"},
                "last_name": {"type": "string"},
                "country": {"type": "string"},
                "age": {"type": "integer"},
                "position": {"type": "string"},
                "market_value": {"type": "integer"},
                "listed_at": {"type": "string", "format": "date-time"}
            }
        },
        "BuyPlayerRequest": {
            "type": "object",
            "required": ["listing_id"],
            "properties": {
                "listing_id": {"type": "integer"}
            }
        },
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {"type": "string"}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Soccer Manager API",
	Description:      "RESTful API for fantasy football manager. Create teams, manage players, and trade on the transfer market.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
